version: '3.8'

services:
  database:
    container_name: blogdb
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blog
    image: postgres:14.5-alpine3.16

  backend:
    container_name: blogbackend
    image: blogbackend
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "5000:2000"
    environment:
      - DB_PORT=5433
      - DB_HOST=127.0.0.1
      - DB_USER=admin
      - DB_PASSWORD=root
      - DB_NAME=blog
    depends_on:
      - database

  frontend:
    container_name: blogfrontend
    image: blogfrontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "5001:3000"

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres:

    