name: Publish on Docker Hub
on:
  push:
    branches: [ main ]
jobs:

  Frontend-Actions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: npm install --prefix ./FrontEnd
    - name: Build project
      run: npm run build --prefix ./FrontEnd
    - name: Test
      run: npm run test --prefix ./FrontEnd


  Backend-Actions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: npm install --prefix ./BackEnd
    - name: Test
      run: npm test --prefix ./BackEnd

  build_and_pub:
    needs: [Backend-Actions, Frontend-Actions]
    runs-on: [ubuntu-latest]
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker-compose build
      - name: Push image to docker.io
        run: docker-compose push
